# Generated by Django 4.2.7 on 2024-01-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_regular_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_no',
            field=models.CharField(default='2fc63c6c', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='productvarients',
            name='color',
            field=models.CharField(choices=[('red', 'RED'), ('blue', 'BLUE'), ('orange', 'ORANGE'), ('none', 'None')], default='none', max_length=50),
        ),
    ]
